theme: jekyll-theme-architect
title: Michiko Ogaku's Homepage
description: I am an Associate Professor of Insurance at Nagasaki University. My research focuses on Mechanism/Information Design and Insurance.
